from .fast_saliency import FastSaliency
from .lcm import LCM
from .hbmlcm import HBMLCM
from .ipi import IPI
from .tophat import Tophat
from .maxmedian import MaxMedian
from .mpcm import MPCM
from .pstnn import PSTNN
from .lcm_custom import LCM_Custom
from .mshnet import MSHNetWrapper